//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfRestSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriorityMaster
    {
        public PriorityMaster()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public int ID { get; set; }
        public string Priority { get; set; }
        public string Description { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
