//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfRestSample
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class TaskSimplerEntities : DbContext
    {
        public TaskSimplerEntities()
            : base("name=TaskSimplerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Book> Books { get; set; }
        public DbSet<MemberMaster> MemberMasters { get; set; }
        public DbSet<PriorityMaster> PriorityMasters { get; set; }
        public DbSet<ProjectMaster> ProjectMasters { get; set; }
        public DbSet<StatusMaster> StatusMasters { get; set; }
        public DbSet<Task> Tasks { get; set; }
    
        public virtual ObjectResult<usp_GetProjects_Result> usp_GetProjects(Nullable<int> memberid)
        {
            var memberidParameter = memberid.HasValue ?
                new ObjectParameter("memberid", memberid) :
                new ObjectParameter("memberid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetProjects_Result>("usp_GetProjects", memberidParameter);
        }
    
        public virtual ObjectResult<usp_getPriority_Result> usp_getPriority(Nullable<int> memberId)
        {
            var memberIdParameter = memberId.HasValue ?
                new ObjectParameter("memberId", memberId) :
                new ObjectParameter("memberId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getPriority_Result>("usp_getPriority", memberIdParameter);
        }
    
        public virtual ObjectResult<usp_GetStatus_Result> usp_GetStatus(Nullable<int> memberid)
        {
            var memberidParameter = memberid.HasValue ?
                new ObjectParameter("memberid", memberid) :
                new ObjectParameter("memberid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetStatus_Result>("usp_GetStatus", memberidParameter);
        }
    }
}
