//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfRestSample.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int ID { get; set; }
        public string TaskName { get; set; }
        public System.DateTime Addedon { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int MemberId { get; set; }
        public Nullable<System.DateTime> StartOn { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
        public int ProjectId { get; set; }
        public int PriorityId { get; set; }
        public int StatusId { get; set; }
        public string Descriptioin { get; set; }
    
        public virtual MemberMaster MemberMaster { get; set; }
        public virtual PriorityMaster PriorityMaster { get; set; }
        public virtual ProjectMaster ProjectMaster { get; set; }
        public virtual StatusMaster StatusMaster { get; set; }
    }
}
